version: '3.8'

services:

  db:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    restart: unless-stopped

  web-server:
    image: php:7.4-apache
    ports:
      - "8081:80"
    volumes:
      - "C:/Users/janua/Git/FHIR_Rebuild/web:/var/www/html"
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  athena_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16